### ISSUE TITLE
RegexMatchers

### ISSUE THREAD

**Issue by carlosmiranda** [jcabi/jcabi-matchers#10]
When I was working on https://github.com/jcabi/jcabi-aspects/pull/88, I needed to create a unit test that used Regex matching as its assertion condition. I realized that Hamcrest did not have built-in matchers for regex. I think it will be very useful if we can have one as standard.

I propose that we create a class `RegexMatchers`, which will initially have the following methods:
- `Matcher<String> matchesPattern(String pattern)`: returns a `Matcher` that checks if the entire string matches the given pattern (should work like the [String.matches() method](http://docs.oracle.com/javase/7/docs/api/java/lang/String.html#matches%28java.lang.String%29)).
- `Matcher<String> containsPattern(String pattern)`: returns a `Matcher` that checks if a string contains a subsequence that matches the given pattern (similar to [Matcher.find() method](http://docs.oracle.com/javase/7/docs/api/java/util/regex/Matcher.html#find%28%29)).

**Comment by dmarkov** [comment]
last puzzled solved `10-8e2f1dc4`/#14
