### ISSUE TITLE
RegexMatchers.java:85-89: Let's create the following convenience...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-matchers#14]
Puzzle `10-8e2f1dc4` in `src/main/java/com/jcabi/matchers/RegexMatchers.java:85-89` has to be resolved: Let's create the following convenience methods: 1) containsAnyPattern(String...patterns), which should pass if a string contains ANY of the given patterns, and 2) containsAllPatterns(String...patterns). which should pass if a string contains ALL of the given patterns.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by darkled** [comment]
@dmarkov PR submitted and merged, please, check it.

**Comment by dmarkov** [comment]
@darkled you're holding this ticket for 12 days already. If it's not finished (and closed) in the next 40 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle... do not forget to remove the TODO puzzle from the source code... -30 added to your rating, at the moment it is: [-45](http://www.netbout.com/b/35091?open=rating)

**Comment by darkled** [comment]
@dmarkov @yegor256 I am not sure these -30 are correct, aren't they?

**Comment by darkled** [comment]
@dmarkov would you mind to close the issue if it is ok now, please?

**Comment by dmarkov** [comment]
@darkled I'll assign someone else, it took too long, please stop immediately; added -60 to your rating, now it is equal to [+150](http://www.netbout.com/b/35091?open=rating)

**Comment by darkled** [comment]
@yegor256 this issues stays without any response from creator for 6 days. Could you help with it, please?

**Comment by darkled** [comment]
fixed within PR #15

**Comment by yegor256** [comment]
@darkled will be closed today or tomorrow the latest

**Comment by darkled** [comment]
@yegor256 thank you

**Comment by darkled** [comment]
@yegor256 still nothing happened with this issue...

**Comment by yegor256** [comment]
@darkled weekend :( check again tomorrow pls

**Comment by darkled** [comment]
@yegor256 there is still no reaction here

**Comment by yegor256** [comment]
@dmarkov please add extra 30 mins to @darkled  account

**Comment by dmarkov** [comment]
> @dmarkov please add extra 30 mins to @darkled  account

@yegor256 I've sent 30 mins extra to @darkled in transaction ID "50517918"

**Comment by darkled** [comment]
@dmarkov won't you close the issue as well?

**Comment by darkled** [comment]
@yegor256 will the issue stay opened?

**Comment by yegor256** [comment]
@dmarkov right, close it pls

**Comment by dmarkov** [comment]
> @dmarkov right, close the ticket pls

@yegor256 OK, sure, closing
