### ISSUE TITLE
rultor fails build but travis passes

### ISSUE THREAD

**Issue by darkled** [jcabi/jcabi-matchers#17]
During merge of PR rultor failed build due to test `NoBrokenLinksTest.findsBrLinksInHtmlWithNamespace` but locally and on travis this test passes successfully. I think these two systems should always provide the same results.

Logs are [here](http://www.rultor.com/t/1489-68992974) and [here](https://travis-ci.org/jcabi/jcabi-matchers/jobs/46127650).

**Comment by dmarkov** [comment]
I'll ask someone to take care of this task soon

**Comment by dmarkov** [comment]
@romankisilenko could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here... The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by dmarkov** [comment]
@darkled many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `50042300`

**Comment by RomanKisilenko** [comment]
@rultor hello

**Comment by RomanKisilenko** [comment]
@rultor merge

**Comment by RomanKisilenko** [comment]
Test and implementation code looks good. 
Probably an issue is related to specific response received from http://www.jcabi.com/broken-link. I would suggest adding more debug output and re-running the build.
Also, is there any way to re-run the rultor build to see if it is a random failure?

**Comment by darkled** [comment]
@RomanKisilenko since next rultor build passed successfully, it seems it is some kind of a random failure. Please, take a look at PR #15.

**Comment by RomanKisilenko** [comment]
Today I was able to reproduce the issue locally and found that this is not a bug in jcabi-matchers. The server responds with 200 OK on http://www.jcabi.com/broken-link. Here is output from wget:
```
ip-192-168-3-104:erc.svn roman$ wget -O - http://www.jcabi.com/broken-link
--2015-01-13 13:19:20--  http://www.jcabi.com/broken-link
Resolving www.jcabi.com... 185.31.19.133
Connecting to www.jcabi.com|185.31.19.133|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9155 (8.9K) [text/html]
Saving to: 'STDOUT'
```

**Comment by dmarkov** [comment]
@romankisilenko just a reminder that you're working with this task for 15 days already; added -30 to your rating, now it is equal to +390

**Comment by RomanKisilenko** [comment]
@darkled Please close this task, as it was solved some time ago.

**Comment by darkled** [comment]
@RomanKisilenko thanks.

**Comment by dmarkov** [comment]
@romankisilenko Thanks a lot, I just topped your account for **30 mins**, transaction ID `50908439`

+30 added to your rating, current score is: +390
