### ISSUE TITLE
Estimate project size

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-matchers#21]
There is no estimate in the project yet. We have to create one as explained [here](https://github.com/teamed/est)

**Comment by dmarkov** [comment]
@super132 it's your task, go ahead

**Comment by super132** [comment]
@dmarkov PR #24 fixed this issue, would you please close it? Thanks.

**Comment by yegor256** [comment]
@rultor deploy

**Comment by dmarkov** [comment]
@yegor256 Closed, thanks all

**Comment by dmarkov** [comment]
@super132 **30 mins** sent to your balance (ID `AP-59A38293LL976510R`), many thanks! It took 142 hours and 21 mins.. added +30 to your rating, now it is equal to [+301](http://www.netbout.com/b/35282?open=rating)
