### ISSUE TITLE
XhtmlMatchers.hasXPaths should print which matcher failed

### ISSUE THREAD

**Issue by krzyk** [jcabi/jcabi-matchers#26]
When matcher fails method `XhtmlMatchers.hasXPaths(String ..xpaths)` prints all of the xpaths that were in the parameters, but it should print just the ones that failed.
Update this method to print only the failed XPaths.

**Comment by dmarkov** [comment]
@yegor256 please dispatch this issue

**Comment by dmarkov** [comment]
@krzyk thanks for the report, I topped your acc for 15 mins, payment ID `69046236`

**Comment by dmarkov** [comment]
@jrdalpra please help, the task is yours

**Comment by jrdalpra** [comment]
@krzyk do you have any test case of it or can you give us an example?

**Comment by jrdalpra** [comment]
@dmarkov the PR #31 is waiting for someone to review. Thanks.

**Comment by krzyk** [comment]
@jrdalpra example:
```
        MatcherAssert.assertThat(
            result, XhtmlMatchers.hasXPaths(
                "//xhtml:div[@id='elapsed' and text() > 0]",
                "//xhtml:div[@id='processors' and text() > 0]",
                "//xhtml:div[@id='freeMemory' and text() > 0]"
            )
        );
```
When e.g. `"//xhtml:div[@id='processors' and text() > 0]"` is not there it will print:
```
Expected: (an XML document with XPath //xhtml:div[@id='elapsed' and text() > 0] and an XML document with XPath //xhtml:div[@id='processors' and text() > 9] and an XML document with XPath //xhtml:div[@id='freeMemory' and text() > 0])
```
but instead it should print:
```
Expected: (an XML document with XPath //xhtml:div[@id='processors' and text() > 9])
```

**Comment by jrdalpra** [comment]
@krzyk can you see the PR #31? Thanks.

On Saturday, January 23, 2016, krzyk <notifications@github.com> wrote:

> @jrdalpra <https://github.com/jrdalpra> example:
>
>         MatcherAssert.assertThat(
>             result, XhtmlMatchers.hasXPaths(
>                 "//xhtml:div[@id='elapsed' and text() > 0]",
>                 "//xhtml:div[@id='processors' and text() > 0]",
>                 "//xhtml:div[@id='freeMemory' and text() > 0]"
>             )
>         );
>
> When e.g. "//xhtml:div[@id='processors' and text() > 0]" is not there it
> will print:
>
> Expected: (an XML document with XPath //xhtml:div[@id='elapsed' and text() > 0] and an XML document with XPath //xhtml:div[@id='processors' and text() > 9] and an XML document with XPath //xhtml:div[@id='freeMemory' and text() > 0])
>
> but instead it should print:
>
> Expected: (an XML document with XPath //xhtml:div[@id='processors' and text() > 9])
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jcabi/jcabi-matchers/issues/26#issuecomment-174156388>
> .
>


-- 
José Volmei Dal Prá Junior - (49) 9112 9359
Bacharel em Ciência da Computação - UnoChapecó
Pós-Graduado em Desenvolvimento de Software Com Java - Unoesc Xxe
Consultor Java e TotalCross
https://github.com/jrdalpra
http://www.kombo.com.br/meucurriculo/jrdalpra
http://www.linkedin.com/in/jrdalpra
msn: jr_dalpra@hotmail.com
skype: jrdalpra
e-mail: jrdalpra@gmail.com

**Comment by jrdalpra** [comment]
@krzyk can you close this issue? Thanks.

**Comment by krzyk** [comment]
@jrdalpra thanks

**Comment by jrdalpra** [comment]
@dmarkov issue closed. Can you close at netbout?

**Comment by jrdalpra** [comment]
@dmarkov Can you check the payment for me? Thanks.

**Comment by jrdalpra** [comment]
@dmarkov @yegor256 @krzyk can you check the payment, please? The PR is merged and issue closed. Thanks.

**Comment by dmarkov** [comment]
> @dmarkov issue closed. Can you close at netbout?

@jrdalpra OK

**Comment by dmarkov** [comment]
@jrdalpra **30 mins** was added to your account, many thanks for your contribution (payment AP-0B544280K6387815G)! The task took 239 hours and 52 mins.

+30 added to your rating, at the moment it is: [+308](http://www.netbout.com/b/36044?open=rating)
