### ISSUE TITLE
XhtmlMatchers.hasXPath throws IllegalArgumentException

### ISSUE THREAD

**Issue by dmzaytsev** [jcabi/jcabi-matchers#29]
`XhtmlMatchers.hasXPath` throws `IllegalArgumentException` for  a valid html fragment
```
MatcherAssert.assertThat(
            "<p>Here is a paragraph.</p><p>New paragraph.</p>",
            XhtmlMatchers.hasXPath("/p[.='Here is a paragraph']")
        );
```

```
[Fatal Error] :1:29: The markup in the document following the root element must be well-formed.

java.lang.IllegalArgumentException: Invalid XML: "<p>Here is a paragraph.</p><p>New paragraph.</p>"
```

**Comment by dmarkov** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@dmzaytsev yeah, but it's not a valid XML. `XhtmlMatchers` work with XML documents, despite the name

**Comment by mohamnag** [comment]
this means this library is not usable against any HTML document. is there an alternative xpath tester for HTML(5?) documents available?
