### ISSUE TITLE
jcabi-matchers vc cactoos-matchers

### ISSUE THREAD

**Issue by paulodamaso** [jcabi/jcabi-matchers#37]
Looks like `jcabi-matchers` and `cactoos-matchers` (https://github.com/llorllale/cactoos-matchers) are two libraries that aim to provide OO hamcrest matchers. ~~Maybe these two libraries should be merged.~~ These two libraries must be merged

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@paulodamaso maybe...

**Comment by paulodamaso** [comment]
@yegor256 Changed the issue description, please take a look,

**Comment by yegor256** [comment]
@paulodamaso we have this one for historical reasons. cactoos-matchers is more powerful, of course

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-matchers#37` is not assigned, can't get performer
