### ISSUE TITLE
Make com.jcabi.matchers.XPathMatcher public

### ISSUE THREAD

**Issue by ilyakharlamov** [jcabi/jcabi-matchers#39]
If someone wants to match XPath with jcabi-matchers the only way to do that is is via 
static XhtmlMatchers.hasXPath()
however, it's static, not OO, not EO.
The jcabi already has a good OO/EO matcher `com.jcabi.matchers.XPathMatcher`, however, it's package-private and cannot be used by any project.

This issue is regarding making com.jcabi.matchers.XPathMatcher public.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@ilyakharlamov you are welcome to make a pull request

**Comment by yegor256** [comment]
@ilyakharlamov I made it public in 1.6.0 see 0bea49c

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-matchers#39` is not assigned, can't get performer
