### ISSUE TITLE
Update parent to 1.25.1

### ISSUE THREAD

**Issue by andreoss** [jcabi/jcabi-matchers#40]
See https://github.com/jcabi/jcabi-http/issues/171 https://github.com/jcabi/jcabi-http/issues/194

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `15`

**Comment by yegor256** [comment]
@rultor release, tag is `1.5`

**Comment by yegor256** [comment]
@rultor release, tag is `1.5`

**Comment by yegor256** [comment]
@rultor release, tag is `1.5`

**Comment by yegor256** [comment]
@rultor release, tag is `1.5`

**Comment by andreoss** [comment]
@yegor256 Now it seems to be the same error as here https://github.com/yegor256/cactoos/issues/1490#issuecomment-724508213 https://github.com/jcabi/jcabi-jdbc/issues/86#issuecomment-725596227

**Comment by yegor256** [comment]
@andreoss nah, it's all good, already released: https://repo.maven.apache.org/maven2/com/jcabi/jcabi-matchers/1.5/ Let's just release once more

**Comment by yegor256** [comment]
@rultor release, tag is `1.5.1`

**Comment by yegor256** [comment]
@andreoss we are all good now, thanks for your contribution! Also, see: https://github.com/jcabi/jcabi-parent/issues/105

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-matchers#40` is not assigned, can't get performer

**Comment by yegor256** [comment]
@rultor release, tag is `1.5.2`

**Comment by yegor256** [comment]
@rultor release, tag is `1.5.3`
